### ISSUE TITLE
Push Notification Plugin for iOS and Android - deprecated

### ISSUE THREAD

**Issue by rpayanm** [signalpoint/push_notifications#12]
I go to https://github.com/phonegap-build/PushPlugin#deprecated-cordova-push-notifications-plugin-for-android-ios-wp8-windows8-blackberry-10-and-amazon-fire-os and said:

> This plugin is deprecated, i.e. it is no longer maintained. Going forward additional features and bug fixes will be added to the new [phonegap-plugin-push](https://github.com/phonegap/phonegap-plugin-push) repository.

Any plan to update this pluging  according to below?

Thank you.

**Comment by signalpoint** [comment]
@rpayanm I am currently working through this same problem with a client. It should be resolved in early January, at which time I'll be included updated documentation for this much needed feature set. In the mean time, if you make any progress please let me know.

**Comment by rpayanm** [comment]
Ok, Thank you so much.

**Comment by rpayanm** [comment]
Good news!
I was able to perform this task. If you want I can make a pull request.

**Comment by signalpoint** [comment]
@rpayanm That is good news. I actually just successfully completed this last week too. Please see my latest commits for changes. If you have a Pull Request, please submit it and we can take a look.

**Comment by rpayanm** [comment]
WOW I did not see that! So I've seen it all sounds good to me.
