### ISSUE TITLE
Token is not deleted if the user logs out

### ISSUE THREAD

**Issue by luxio** [signalpoint/push_notifications#19]
If the user logs out, the token is not deleted.

**Comment by signalpoint** [comment]
@luxio It should work if they have permission: https://github.com/signalpoint/push_notifications/blob/7.x-1.x/push_notifications.js#L31

However, you may need to grant anonymous users permission to delete the token to get it to work, or we could move this deletion as a services user logout pre processor.

Thoughts?

**Comment by luxio** [comment]
I have granted anonymous users permission to delete the token, but it is not beeing deleted. 

> we could move this deletion as a services user logout pre processor.

This would make sense, because `push_notifications_delete_device_token()` is only called as anonymous user at the moment.

**Comment by luxio** [comment]
Afte a user logs out  `Drupal.user` ist set to `drupal_user_defaults()` so `user_access()` at https://github.com/signalpoint/push_notifications/blob/7.x-1.x/push_notifications.js#L31 will always return false, because `Drupal.user.permissions` is empty. 

I think `push_notifications_delete_device_token()` should be called in the services user logout pre processor.

**Comment by luxio** [comment]
I have created a pull quest: #20

**Comment by signalpoint** [comment]
@luxio Agree. Thank you for the pull request, I have merged it in.
