### ISSUE TITLE
drupalgap push notifications module not loading

### ISSUE THREAD

**Issue by signalpoint** [signalpoint/push_notifications#2]
Posted by eudaemonia on October 13, 2014 at 6:40pm
https://www.drupal.org/node/2355997

I have push notifications installed at www/app/modules/push_notifications/push_notifications.js. I have it listed in my setting.js as Drupal.modules.contrib['push_notifications'] = {};

I installed the push notifications module on my site, got a google cloud messaging api, put the key in the config as instructed. I pasted my GCM Sender ID in the push_notifications.js at the top as instructed.

When I build/run android I get the error Failed to load module! (push_notifications)

Any ideas why? I noticed that notifications is spelled "notificiations" a few times in the code. Could that be impacting performance?

Thanks in advance for your help and ideas!

**Comment by daode** [comment]
interested in the answer to this problem. thank you

**Comment by signalpoint** [comment]
@scotthooker may be able to shed some light on this.

**Comment by daode** [comment]
just for information, without apparent error on the modules, no token recorded at the site.

and as it is on the phone, we have no opportunity to see the logs.

**Comment by ptmkenny** [comment]
@daode It is possible to see the logs, at least on Android:
(from http://drupalgap.org/debug)
Debugging a compiled app's console.log

When compiling an app to your phone over USB using the PhoneGap (Cordova) Command Line Interface (CLI), it can be handy to view the JavaScript console.log(). Run this terminal command after your app is running in debug mode:

adb shell logcat | grep 'Web Console'

**Comment by mkinnan** [comment]
I am having this problem. In ripple emulator, console log is showing:

`push_notifications_services_postprocess - ReferenceError: PushNotification is not defined`

When I compile the app, I get an alert message as soon as the app loads on my phone:

`Failed to load module! (push_notifications)`

Was there a resolution to this?

**Comment by mkinnan** [comment]
The **Failed to load module!** issue seems to be related to permissions. If your app doesn't have permission for notifications, i get the error. Correcting the permissions made the app load with no issues. I am compiling on Adobe Phonegap Build. Make sure in your config.xml file you remove this line before compiling:

`<preference name="permissions"                value="none"/>`

**Comment by signalpoint** [comment]
This module has since been updated a whole bunch, and combined with @mkinnan 's suggestions, this issue is resolved.
