### ISSUE TITLE
Support for Firebase Cloud Messaging

### ISSUE THREAD

**Issue by akolahi** [signalpoint/push_notifications#24]
I initially installed the http://drupalgap.org/project/fcm drupalgap module along with the firebase cloud messaging patch to Push Notifications Drupal module https://www.drupal.org/node/2761401.  Seemed to work okay, except notifications were only received when app is open.

I learned that http://drupalgap.org/project/fcm is not supported and is better to use this module.

Uninstalled FCM and installed this module, however doesn't appear to work at all with the Firebase Cloud Messaging patch stated above.  Appears tokens are not registering now, though they were registering with FCM phonegap module. Given that Google only supports Firebase for new projects, i have no choice but to use it.

How can this module support FCM?

Thank you.

**Comment by akolahi** [comment]
Spoke too soon.  Looks like it's working fine :)

**Comment by signalpoint** [comment]
@akolahi I had forgot about http://drupalgap.org/project/fcm, that project is pretty much identical to push_notifications, instead it uses that fcm plugin for phonegap. I'd recommend using the fcm project for DrupalGap instead of push_notifications. Did one or both work for you?

**Comment by akolahi** [comment]
So far i have only tested Android, but from what i see so far looks like drupalgap push_notifications is working fine with the above Drupal Push Notifications FCM patch with no modifications. I will update here as i test more.

**Comment by akolahi** [comment]
Working like a charm.  No issues :)

**Comment by luxio** [comment]
> Working like a charm. No issues :)

Which module are you using? [Firebase Cloud Messaging](http://drupalgap.org/project/fcm) or [Push Notifications](http://drupalgap.org/project/push_notifications)? 

[Push Notifications](http://drupalgap.org/project/push_notifications) works fine with iOS, but now I want to add support for Android and would like to know, if have to replace the DG modul.

**Comment by mkinnan** [comment]
I'm a bit confused as to why a new module was developed instead of updating current module to support GCM and FCM.

**Comment by mkinnan** [comment]
@luxio ... I'm using push notifications module successfully on iOS and Android. The only thing i cannot figure out and get to work is message stacking ... I posted this in another issue for push notifications module.

**Comment by luxio** [comment]
@mkinnan thanks.  Are you using FCM or GCM?

**Comment by mkinnan** [comment]
@luxio ... I'm using GCM with this plugin ...

https://www.npmjs.com/package/phonegap-plugin-push

I haven't sat down yet to update my drupal website module since the dev version has support for FCM now.

**Comment by luxio** [comment]
@mkinnan as Google requires to use FCM for new projects I will check, if FCM works with the DG Push Notification module.
