### ISSUE TITLE
Push notification not working for android

### ISSUE THREAD

**Issue by kiss-jozsef** [signalpoint/push_notifications#3]
If you have an android device and try to register it push_notifications_platform_token function return null so the push_notificiations_create will return error i added an extra case for android 
case "Android":
      token = 'android';
      break;
and this solves it

**Comment by signalpoint** [comment]
@kiss-jozsef Excellent, thank you. Please fork this repository, and submit a pull request with the fix, and we can merge it in for your contribution!

**Comment by ptmkenny** [comment]
@kiss-jozsef Did this fix ever get added to the push_notifications project?

**Comment by kiss-jozsef** [comment]
@ptmkenny yes it was added

**Comment by ptmkenny** [comment]
@kiss-jozsef  Ok, thanks.  Just wanted to check because this issue was never marked resolved.

**Comment by signalpoint** [comment]
This module has since been updated heavily and well documented, this should no longer be an issue.
