### ISSUE TITLE
Push notification retrieve message data

### ISSUE THREAD

**Issue by kiss-jozsef** [signalpoint/push_notifications#5]
There is the possibility to pass parameters in the notification but in the onNotificationGCM() function the 'message' case does nothing can we retrieve the passed data in some other way? (if not i would suggest adding localStorage.setItem('push_notifications_message', JSON.stringify(e)); or something similar).

The other issues is that you can retrieve the message only if you are logged in , but on every login/logout the device token gets deleted and a new one is made is there a reason for this?

**Comment by signalpoint** [comment]
@scotthooker may be able to shed some light on this.

**Comment by signalpoint** [comment]
The module has since been expanded and well documented. Retrieving the message data and custom payloads is now covered in the README.
